title: "100 Days of Yara in 2024: Day 39" 
description: "Parsing LC_VERSION_MIN_* Load Commands for Mach-O in YARA-X..again!"
date: "2024-02-08"
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source