title: "YARA-X: Exploring the Python Bindings"
description: "It's time to explore the YARA-X bindings for Python. Scan, compile, use modules, and more!"
date: '2024-03-21'
categories:
    - YARA-X
    - software engineering
    - Python