title: "100 Days of Yara in 2024: Day 33" 
description: "Opening a PR to a different repo (not YARA-X)!"
date: "2024-02-02"
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - maintenance
