title: "100 Days of Yara in 2024: Day 07" 
description: Generating and Formatting the Files needed for YARA-X Mach-O Testing
date: '2024-01-07'
categories:
    - YARA-X
    - 100-days-of-yara
    - 100-days-of-yara-2024 
    - Mach-O
    - Testing