title: "100 Days of Yara in 2024: Day 38" 
description: "Parsing LC_BUILD_VERSION for Mach-O in YARA-X..again!"
date: "2024-02-07"
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source