title: "100 Days of Yara in 2024: Day 16" 
description: "Collaborating on a Pull Request for YARA-X: Documentation Edition"
date: '2024-01-16'
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - Maintenance