title: "100 Days of Yara in 2024: Day 19" 
description: "Parsing the code signature for Mach-O binaries!!"
date: '2024-01-19'
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - certificates
    - code signature