title: "100 Days of Yara in 2024: Day 18" 
description: "Parsing the Code Signature data of a Mach-O binary: a WIP"
date: '2024-01-18'
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source