title: "100 Days of Yara in 2024: Day 28" 
description: "Big changes to the Mach-O module in YARA-X internally"
date: '2024-01-28'
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - Planning