title: "100 Days of Yara in 2024: Day 41" 
description: "Parsing Tries in a Mach-O for exports!"
date: "2024-02-10"
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - data structure
