title: "100 Days of Yara in 2024: Day 09"
description: Implementing a function to search dylibs for a specified path for the Mach-O Module
date: '2024-01-08'
categories:
    - YARA-X
    - 100-days-of-yara
    - 100-days-of-yara-2024 
    - Mach-O