title: "100 Days of Yara in 2024: Day 20" 
description: "Planning the route ahead for the next features of Mach-O with YARA-X"
date: '2024-01-20'
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - Planning