title: "100 Days of Yara in 2024: Day 21"
description: "Parsing more Code Signature Data on Mach-O: Entitlements"
date: '2024-01-21'
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - Mach-O