title: "100 Days of Yara in 2024: Day 17" 
description: "Beginning to parse code signature data? Maybe?"
date: '2024-01-17'
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - Load_Command