title: "100 Days of Yara in 2024: Day 31" 
description: "Parsing Code Signing Certificates in YARA-X..again!"
date: "2024-01-31"
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
