title: "100 Days of Yara in 2024: Day 29" 
description: "Looking at the recent Mach-O module changes in YARA-X"
date: "2024-01-29"
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
