title: "100 Days of Yara in 2024"
description: "How long is 100 days really? I wrote down some of my thoughts on it."
date: '2023-12-30'
categories:
    - YARA
    - YARA-X
    - 100-days-of-yara-2024