title: "100 Days of Yara in 2024: Day 14" 
description: Parsing the symbol table for Mach-O binaries 🍏
date: '2024-01-14'
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Mach-O
    - Load_Command
    - Symbol Table