title: "100 Days of Yara in 2024: Day 35" 
description: "Parsing LC_SYMTAB in YARA-X..again!"
date: "2024-02-04"
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - symbol table
