title: "100 Days of Yara in 2024: Day 36" 
description: "Parsing LC_SYMTAB entries in YARA-X..again!"
date: "2024-02-05"
categories:
    - YARA-X
    - 100-days-of-yara-2024 
    - Open Source
    - symbol table
