title: "100 Days of Yara in 2024: Day 02"
description: "Chores and More!"
date: '2024-01-02'
categories:
    - YARA-X
    - 100-days-of-yara
    - Open Source
    - Maintenance
    - 100-days-of-yara-2024